### ISSUE TITLE
Using R 4.2 `Rscript -e "renv::restore()"` aborts on installation of "stringi"

### ISSUE THREAD

**Issue by macrobiotus** [genner-lab/meta-fish-lib#25]
Hello, 

thanks for doing this great work - loving it! I am currently trying to adjust a fork at [https://github.com/macrobiotus/meta-fish-lib-nz](https://github.com/macrobiotus/meta-fish-lib-nz). I am running R 4.2 and can't seem to get your shell script to work, in the lower part of your `README.md`. Any ideas for a quick fix?

```
### install required R packages using renv (only need to run this once) ###
Rscript -e "renv::restore()" # aborts on installation of "stringi"

# trying to alleviate - no luck
Rscript -e "renv::status()"
Rscript -e 'install.packages("stringi")'
Rscript -e 'renv::restore(exclude = c("stringi"))'
```

<img width="833" alt="Screen Shot 2022-09-29 at 01 23 50" src="https://user-images.githubusercontent.com/10920135/192905662-4550b4ac-cca8-459f-ae82-68d359e6cc77.png">

```
system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0
     
      
```
```
> sessionInfo() 
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur/Monterey 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0    renv_0.14.0   

```

**Comment by boopsboops** [comment]
Hi Paul,

Glad you are using meta-fish-lib! 

I was able to reproduce your error. It looks like stringi v1.7.3 is not compatible with R v4.2.0. 

I did get it working on R v4.2.0 by deleting the stringi and Hmisc packages in the `renv.lock` file. I've attached a new version here. Change the name back to 'renv.lock' from renv.lock.txt' (GitHub won't allow it with just .lock for some reason) and replace the existing one with this one.

If that doesn't work for you, I will get around to updating all the packages to be compatible with R v4.2 at some point, but in the meantime I suggest reverting to R v4.1.1 as this was the version that the code has been tested on.

What I do to manage R versions is use software called [renv-installer](https://github.com/jcrodriguez1989/renv-installer). Confusingly, this has nothing to do with the renv package manager that is used to install the R packages, and is separate bash software that lets you install multiple R versions side-by-side on your machine. It's well worth investing the time to set up, as you can then use different R versions on different projects, and things don't break when you update.

Hope this helps.

[renv.lock.txt](https://github.com/genner-lab/meta-fish-lib/files/9677962/renv.lock.txt)

**Comment by macrobiotus** [comment]
Dear Rupert,

Thank you for your swift reply. I will do as you suggest thank you for the effort. Luckily I had another computer with R 4.1 so was able to progress past this error now. 

I now gave the next issue, if not being able to connect to NCBI, a domain has changed meanwhile. It would appear, but I’ll log an issue tomorrow to keep things neat. I may fork this repo for NZ and give you credit.

I find you write excellent code there it was a pleasure to look at.

Kind regards,

Paul

www.drpaulc.info

**Comment by boopsboops** [comment]
Excellent. Glad that problem is fixed. I'll reply about the NCBI issue in the other Issue.

**Comment by macrobiotus** [comment]
👍


Sent from my Apple Watch
