### ISSUE TITLE
Perhaps unintentionally `hmmer` needs to be installed manually. 

### ISSUE THREAD

**Issue by macrobiotus** [genner-lab/meta-fish-lib#27]
Perhaps unintentionally `hmmer` needs to be installed manually.  `sh: nhmmer: command not found` can be alleviated by running ` brew install hmmer` on mac. Might be intentional behaviour, discard issue if desired. Thank you for your support so far.

**Comment by macrobiotus** [comment]
Probably intentional, non-issue.

**Comment by boopsboops** [comment]
Yes, the hmmer, mafft and raxml-ng software all need installing manually, as they are not provided with any R packages. All should be available on homebrew.

FYI, I just did a pretty big update to the code, improved a few functions and upgraded R and packages to R v4.2.1. Might be good to merge these into your fork.

**Comment by macrobiotus** [comment]
Thank you Rupert, will check and do if I can get it to merge.
