### ISSUE TITLE
Is there any way for chinease users to increase download speeds？

### ISSUE THREAD

**Issue by marineLZ** [genner-lab/meta-fish-lib#5]
I have tried many times but failed in steps “scripts/sequences-download.R” , e.g. The process stayed in "Results returned for 8 queries. Search took 1.49 seconds." and did not change any more.

ow searching GenBank on 8 cores ...

Results returned for 8 queries. Search took 1.92 seconds.
Results returned for 8 queries. Search took 2.47 seconds.
Results returned for 8 queries. Search took 1.28 seconds.
Results returned for 8 queries. Search took 1.98 seconds.
Results returned for 8 queries. Search took 2.06 seconds.
Results returned for 8 queries. Search took 1.79 seconds.
Results returned for 8 queries. Search took 1.83 seconds.
Results returned for 8 queries. Search took 2.36 seconds.
Results returned for 8 queries. Search took 1.81 seconds.
Results returned for 8 queries. Search took 2.17 seconds.
Results returned for 8 queries. Search took 1.38 seconds.
Results returned for 8 queries. Search took 1.97 seconds.
Results returned for 8 queries. Search took 1.41 seconds.
Results returned for 8 queries. Search took 1.9 seconds.
Results returned for 8 queries. Search took 2.03 seconds.
Results returned for 8 queries. Search took 2.08 seconds.
Results returned for 8 queries. Search took 1.96 seconds.
Results returned for 8 queries. Search took 1.94 seconds.
Results returned for 8 queries. Search took 1.66 seconds.
Results returned for 8 queries. Search took 2.14 seconds.
Results returned for 8 queries. Search took 1.76 seconds.
Results returned for 8 queries. Search took 1.83 seconds.
Results returned for 8 queries. Search took 2.32 seconds.
Results returned for 8 queries. Search took 2.08 seconds.
Results returned for 8 queries. Search took 2.25 seconds.
Results returned for 8 queries. Search took 2.39 seconds.
Results returned for 8 queries. Search took 2.2 seconds.
Results returned for 8 queries. Search took 2.23 seconds.
Results returned for 8 queries. Search took 1.86 seconds.
Results returned for 8 queries. Search took 2.19 seconds.
Results returned for 8 queries. Search took 2.04 seconds.
Results returned for 8 queries. Search took 1.26 seconds.
Results returned for 8 queries. Search took 2.26 seconds.
Results returned for 8 queries. Search took 2.13 seconds.
Results returned for 8 queries. Search took 1.78 seconds.
Results returned for 8 queries. Search took 2.15 seconds.
Results returned for 8 queries. Search took 1.95 seconds.
Results returned for 8 queries. Search took 2.18 seconds.
Results returned for 8 queries. Search took 2.55 seconds.
Results returned for 8 queries. Search took 1.93 seconds.
Results returned for 8 queries. Search took 1.77 seconds.
Results returned for 8 queries. Search took 2.13 seconds.
Results returned for 8 queries. Search took 1.49 seconds.

**Comment by boopsboops** [comment]
Hi there. 

Do you have an API key for NCBI, and created `assets/ncbi-key.R`? This makes is faster.

Also, have you tried on fewer cores (e.g. `-t 4`)? Perhaps the request rate is too fast with 8 cores.

This often depends on the time of day, unfortunately. Try running when the USA is asleep.

Let me know if this works.

Cheers

**Comment by marineLZ** [comment]
Dear boopsboops， 

Thanks for your prompt responses and excellent pipeline！ I had already used  API key. 

Now I reduce the query to 50 species to test the following steps . It succeeded in download sequences.  But in references-assemble.R -t 2 :
Error: <github_error in gh_process_response(raw):
GitHub API error (401):
Message: Bad credentials
Read more at https://docs.github.com/rest>

How could I solve this problem?

**Comment by marineLZ** [comment]
Sometimes this error：

scripts/references-assemble.R -t 2
WARNING: ignoring environment value of R_HOME

Packages and functions loaded

Extracting metabarcode fragments with HMMER (may take several minutes) ...

Done

Retrieving metadata from NCBI ...

Retrieving sequence IDs...
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
Parsing...
...done
Retrieving sequence IDs...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Parsing...
...done
Retrieving sequence IDs...
Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  预定内核2的用户代码中出了错，所有作业值都将受到影响
Time difference of 36.15717 secs

NCBI metadata sucessfully retrieved

Now cleaning data ...
Error: Argument 2 must have names.
Backtrace:
    █
 1. ├─tibble::as_tibble(bind_rows(ncbi.frag))
 2. └─dplyr::bind_rows(ncbi.frag)
停止执行

**Comment by boopsboops** [comment]
If you try with 75 species, does that work?

If you still get the error, can you run the script line-by-line to find out exactly where the error is occurring please.

Cheers

**Comment by boopsboops** [comment]
It looks like a problem with rfishbase. See https://github.com/ropensci/rfishbase/issues/216

Try to either use their fix, or update rfishbase with `renv::install(packages="rfishbase@3.1.9")`

**Comment by marineLZ** [comment]
Another errors:

scripts/references-assemble.R -t 2
WARNING: ignoring environment value of R_HOME

Packages and functions loaded

Extracting metabarcode fragments with HMMER (may take several minutes) ...

Done

Retrieving metadata from NCBI ...

Retrieving sequence IDs...
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
Parsing...
...done
...done
Retrieving sequence IDs...
Parsing...
...done
Time difference of 36.82188 secs

NCBI metadata sucessfully retrieved

Now cleaning data ...
Error in curl::curl_download(addr, dest = local_tbl) :
  HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
Calls: <Anonymous> ... select -> mutate -> fb_tbl -> db_create -> <Anonymous>
停止执行
(meta-fish-lib) [zhoulei@zhoulab meta-fish-lib]$ scripts/references-assemble.R-t 2
WARNING: ignoring environment value of R_HOME

Packages and functions loaded

Extracting metabarcode fragments with HMMER (may take several minutes) ...

Done

Retrieving metadata from NCBI ...

Retrieving sequence IDs...
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Retrieving sequence IDs...
Parsing...
...done
Parsing...
...done
Time difference of 35.97748 secs

NCBI metadata sucessfully retrieved

Now cleaning data ...
Error in curl::curl_download(addr, dest = local_tbl) :
  HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
Calls: <Anonymous> ... select -> mutate -> fb_tbl -> db_create -> <Anonymous>
停止执行

**Comment by boopsboops** [comment]
Maybe restart the machine and try again.

**Comment by marineLZ** [comment]
Thanks. Problems solved!
