### ISSUE TITLE
"reference-library-master.csv.gz" file for China or other coutry

### ISSUE THREAD

**Issue by marineLZ** [genner-lab/meta-fish-lib#7]
Dear boopsboops,  Finally I find it difficult to download sequences in NCBI for Chinese users (when query is relative big) even in weekends. Could you upload "reference-library-master.csv.gz" file for China or other country?

**Comment by boopsboops** [comment]
Hi there. Some questions:

You need a reference library for all Chinese fish species, correct? 

How many total species is that? 

Are you searching for synonyms also?

Which metabarcode region(s) do you require?

Cheers

**Comment by boopsboops** [comment]
Hi there. 

I have updated the code to include some new options that will speed up the search and make it more efficient: an "-e" option for `scripts/sequences-download.R` that disables the exhaustive search if set to "false". This should still give you 99% of the sequences, but will take much less time and consume less RAM and disk space. There is also an "-m" option for the `scripts/references-assemble.R` step that allows you to choose which metabarcodes to include, making the pipeline hopefully more efficient. 

Please clone/download/pull a new version of the repository and see if this works better. There is also a small test dataset you can use to make sure everything is working. Run as below and then continue with the remaining steps:

`scripts/sequences-download.R -l assets/species-table-testing.csv -t 4 -e false` 

Cheers

**Comment by marineLZ** [comment]
Oh, beautiful.  Thanks. I will try soon. 

By the way, how can I get the full-length 12S or CO1 gene (or the fragment as it is  in the database, that is not extract with the primer). For me, it will be more suitable for phylogenetic quality control compared with short fragments. In training feature classifiers,  some taxa (e.g. fungi) do NOT benefit from extracting/trimming reads to primer sites. Further we could extract reference reads by the primers in tools like Qiime2 to train feature classifier.

**Comment by marineLZ** [comment]
See document in https://docs.qiime2.org/2021.2/tutorials/feature-classifier/

**Comment by boopsboops** [comment]
If you need complete genes for fishes, then probably the best solution is to obtain these from the MitoFish website at http://mitofish.aori.u-tokyo.ac.jp/

You are right that phylogenetic quality control will be better with longer fragments, but the problem is that for many species, there are only very short fragments available, so some could be missed entirely if you choose only long sequences. 

Indeed, it's often desirable to not trim the primer sites from the metabarcodes. I have actually made hidden Markov models for the markers with primers attached, and these can be found at https://github.com/boopsboops/reference-libraries/tree/master/hmms

For example: `12s.miya.primers.hmm` will include the priming sites. Try using these instead of the current ones in meta-fish-lib named e.g. `12s.miya.noprimers.hmm` and then change the prefixes in `scripts/references-assemble.R` from ".noprimers" to ".primers". You may need to then length filter them after.

Hope this helps.

**Comment by marineLZ** [comment]
Thanks, boopsboops. I succeed in running the test dataset in the new version. It  takes much less time than before. But in download my own sequecnes, some errors appeared as follows: 

....
Results returned for 2 queries. Search took 11.47 seconds.
Time difference of 47.48612 mins

All search batches successful

Now downloading 413885 sequences from GenBank ...
Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
Time difference of 12.56294 mins

All sequences sucessfully downloaded

Writing out in FASTA format ...
Error in FUN(X[[i]], ...) :
  data are apparently neither DNA nor AA sequences
Calls: suppressMessages -> withCallingHandlers -> lapply -> FUN

**Comment by marineLZ** [comment]
I have tried many times and run the commands line by line. Only the sequences of testdata can be downloaded successful. When comes to my own data, whether the cores setted to 2 or 4 , warnings: In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule, :
all scheduled cores encountered errors in user code

**Comment by boopsboops** [comment]
Hi there. Sorry it's still not working for your data. 

It is strange that the error occurred, but then the downloaded sequences were still "successfully downloaded" (i.e. they were DNAbin objects).

To find out the cause, try breaking up your species list into 10% chunks, run each, and see which chunk the error occurs in. If the error is reproducible, then it is possible to fix it.

Also, can you link to your species list table please, and I can take a look? 

Cheers

**Comment by marineLZ** [comment]
Hi, boopsboops. Sorry for disturbing you again and again.  I don't know how to upload my specieslist, it has more than 10k species (including synoymns).

tested by a small subset of my species, I found that the mclapply problem in download step is caused by not enough tempfile space.
The solution is : 
#change the tempdir() location
tempdir <- function() "/data/Rtmp"
unlockBinding("tempdir", baseenv())
utils::assignInNamespace("tempdir", tempdir, ns="base", envir=baseenv())
assign("tempdir", tempdir, baseenv())
lockBinding("tempdir", baseenv())

Further, in assembly step, the solution is set the HTTP version to 1.1 (none, 1.0, 1.1, 2):
library("httr")
httr::set_config(config(http_version = 2)) 

I will test the whole of my species list later!

Thank you!

**Comment by boopsboops** [comment]
Ah, I was going to suggest a disk problem. Are you monitoring system RAM as the script runs? Is that RAM running out?

Perhaps I can write this part so that the sequences aren't held in RAM, but written straight to file in one step. Should eliminate this problem.

**Comment by marineLZ** [comment]
Probably，it's my ROM that store tempfiles running out as my server's RAM is 512 G . The function store tempfiles in /tmp path by defaults. There is only 30G left in /tmp path.

**Comment by boopsboops** [comment]
I have changed the `read_GenBank` function to write to a tempdir in the project temp folder called `temp/fasta-temp`, rather than the default. 6d1fb00e8766572366eef17b10a21278ceabc682
